### ISSUE TITLE
NetworkPolicy V1 does not work for Kubernetes 1.7

### ISSUE THREAD

**Issue by gyliu513** [projectcalico/k8s-policy#108]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I set up the network policy according to https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/ with network v1 policy, but it is not working.

**What you expected to happen**:
The pod should be isolated by network policy.

**How to reproduce it (as minimally and precisely as possible)**:
calicoctl version:

```
root@k8s001:~/calico-2.3# calicoctl version
Version:      v1.3.0
Build date:
Git commit:   d2babb6
```

calico node version:
```
quay.io/calico/node:v1.3.0
```

calico controller:
```
quay.io/calico/kube-policy-controller:v0.6.0
```

Caclio nodes:
```
root@k8s001:~# calicoctl get nodes
NAME
k8s001
k8s004
```

Calico node status on k8s001 which is master and worker node:
```
root@k8s001:~# calicoctl node status
Calico process is running.

IPv4 BGP status
+---------------+-------------------+-------+----------+-------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+---------------+-------------------+-------+----------+-------------+
| 192.168.56.14 | node-to-node mesh | up    | 09:39:17 | Established |
+---------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.
```

Calico node status on k8s004 which is worker node:
```
root@k8s004:~# calicoctl node status
Calico process is running.

IPv4 BGP status
+---------------+-------------------+-------+----------+-------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+---------------+-------------------+-------+----------+-------------+
| 192.168.56.11 | node-to-node mesh | up    | 09:39:17 | Established |
+---------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.
```

Cluster Status:
```
root@k8s001:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.1.685+950a09d982286a", GitCommit:"950a09d982286a32a045f956d91680e0defd71dd", GitTreeState:"clean", BuildDate:"2017-07-02T11:23:13Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.1.685+950a09d982286a", GitCommit:"950a09d982286a32a045f956d91680e0defd71dd", GitTreeState:"clean", BuildDate:"2017-07-02T11:23:13Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
root@k8s001:~# kubectl get nodes --show-labels
NAME      STATUS    AGE       VERSION                             LABELS
k8s001    Ready     54m       v1.8.0-alpha.1.685+950a09d982286a   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=k8s001
k8s004    Ready     16m       v1.8.0-alpha.1.685+950a09d982286a   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=k8s004
root@k8s001:~# kubectl get pods --namespace=kube-system -owide
NAME                                        READY     STATUS    RESTARTS   AGE       IP              NODE
calico-policy-controller-2862571771-50kzl   1/1       Running   0          54m       192.168.56.11   k8s001
kube-dns-v20-2397184141-7hgcv               3/3       Running   0          19m       192.168.191.0   k8s001
root@k8s001:~# kubectl get pods
No resources found.
```

Start to follow https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/ to test network policy:

```
root@k8s001:~# kubectl run nginx --image=nginx --replicas=2
deployment "nginx" created
root@k8s001:~/cases# kubectl expose deployment nginx --port=80
service "nginx" exposed
root@k8s001:~# kubectl get pods -owide
NAME                    READY     STATUS    RESTARTS   AGE       IP                NODE
nginx-374391258-0ljg4   1/1       Running   0          1m        192.168.191.4     k8s001
nginx-374391258-qmzj4   1/1       Running   0          1m        192.168.124.131   k8s004
root@k8s001:~# kubectl get svc,pod
NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
svc/kubernetes   ClusterIP   10.254.0.1      <none>        443/TCP   59m
svc/nginx        ClusterIP   10.254.24.218   <none>        80/TCP    14m

NAME                       READY     STATUS    RESTARTS   AGE
po/nginx-374391258-0ljg4   1/1       Running   0          1m
po/nginx-374391258-qmzj4   1/1       Running   0          1m
```

Create a network policy.
```
root@k8s001:~/cases/network-policy# cat ns.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-nginx
spec:
  podSelector:
    matchLabels:
      run: nginx
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access: "true"
```

```
root@k8s001:~/cases/network-policy# kubectl create -f ./ns.yaml
networkpolicy "access-nginx" created
root@k8s001:~/cases/network-policy# kubectl get networkpolicies
NAME           POD-SELECTOR   AGE
access-nginx   run=nginx      8s
```

Create a pod without correct labels, still works:
```
root@k8s001:~/cases/network-policy# kubectl run busybox --rm -ti --image=busybox /bin/sh
If you don't see a command prompt, try pressing enter.
/ # wget --spider --timeout=1 nginx
Connecting to nginx (10.254.24.218:80)
```

While the above `wget` in busybox container should be failed as it does not have the ingress rules requested labels.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
```
root@k8s001:~/cases/network-policy# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
root@k8s001:~/cases/network-policy# uname -a
Linux k8s001 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:

- Others:

**Comment by gyliu513** [comment]
I was following the steps here http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/integration to install calico 2.3

**Comment by gyliu513** [comment]
The default deny policy also does not work

```
root@k8s001:~/calico-2.3# cat deny.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector:
```

**Comment by gyliu513** [comment]
After I create the access control policy, I found that the profile is empty.
```
root@k8s001:~/calico-2.3# cat access-true.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-nginx
spec:
  podSelector:
    matchLabels:
      run: nginx
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access: "true"
root@k8s001:~/calico-2.3# kubectl create -f ./access-true.yaml
networkpolicy "access-nginx" created
root@k8s001:~/calico-2.3# calicoctl get profile  k8s_ns.default  -o yaml
- apiVersion: v1
  kind: profile
  metadata:
    name: k8s_ns.default
    tags:
    - k8s_ns.default
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
```

2. Create a deny network policy, also does not work.
```
root@k8s001:~/calico-2.3# kubectl delete -f ./access-true.yaml
networkpolicy "access-nginx" deleted
root@k8s001:~/calico-2.3# calicoctl get profile  k8s_ns.default  -o yaml
- apiVersion: v1
  kind: profile
  metadata:
    name: k8s_ns.default
    tags:
    - k8s_ns.default
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
root@k8s001:~/calico-2.3# cat deny.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector:
root@k8s001:~/calico-2.3# kubectl create -f ./deny.yaml
networkpolicy "default-deny" created
root@k8s001:~/calico-2.3# calicoctl get profile  k8s_ns.default  -o yaml
- apiVersion: v1
  kind: profile
  metadata:
    name: k8s_ns.default
    tags:
    - k8s_ns.default
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
```

The ingress action is always allow, can anyone help check what is wrong?

**Comment by gyliu513** [comment]
It is really strange that Kubernetes 1.8 still works:

```
root@k8s001:~# kubectl annotate ns default "net.beta.kubernetes.io/network-policy={\"ingress\": {\"isolation\": \"DefaultDeny\"}}"
namespace "default" annotated
root@k8s001:~# kubectl get ns -oyaml default
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    net.beta.kubernetes.io/network-policy: '{"ingress": {"isolation": "DefaultDeny"}}'
  creationTimestamp: 2017-07-18T09:00:38Z
  name: default
  resourceVersion: "88235"
  selfLink: /api/v1/namespaces/default
  uid: 91ac769b-6b97-11e7-b85e-08002759511a
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
root@k8s001:~# calicoctl get profile
NAME
k8s_ns.default
k8s_ns.kube-public
k8s_ns.kube-system

root@k8s001:~# calicoctl get profile k8s_ns.default -oyaml
- apiVersion: v1
  kind: profile
  metadata:
    name: k8s_ns.default
    tags:
    - k8s_ns.default
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: deny
      destination: {}
      source: {}
```

Run above case, wget failed
```
root@k8s001:/opt/bin# kubectl run busybox --rm -ti --image=busybox /bin/sh
If you don't see a command prompt, try pressing enter.
/ # wget --spider --timeout=1 nginx
Connecting to nginx (10.254.24.218:80)
wget: download timed out
```

**Comment by discsthnew** [comment]
i meet the same problem in kubernets1.7.0  too, is there any solution?

**Comment by gyliu513** [comment]
I think this is a very serious issue as the Calico Network Policy is not working, can anyone help take a look?

**Comment by gunjan5** [comment]
@gyliu513 @discsthnew NetworkPolicy V1 is only implemented with `kubernetes` backend datastore in `quay.io/calico/node:v1.3.0` , not with etcd backend. It will be supported for etcd backend in the next release soon.

**Comment by gyliu513** [comment]
How can I configure `kubernetes` backend? Any document that I can follow? @gunjan5

**Comment by gunjan5** [comment]
@gyliu513 http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/hosted/kubernetes-datastore/

**Comment by gyliu513** [comment]
Seems it has many limitations now and I may do not want to switch to this mode now. 

One more question, in the kubernetes changelog, it mentioned that the annotations was already removed in kubernetes 1.7 https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#network , but I did some test with `net.beta.kubernetes.io/network-policy` on Kubernetes 1.7, it still works, is this expetced? @gunjan5

**Comment by gunjan5** [comment]
That is just a namespace annotation, I think what they mean by "revoked" is that it's not included in the V1 spec. If you're using Calico etcd backend v2.3 or older it still watches for that annotation and will act according to pre-V1 policy spec (which still respects the annotation). K8s 1.7 doesn't actually get rid of the namespace annotation, it just adds a v1 network policy endpoint and also keeps the v1beta1 endpoint around. Short answer, yes that's expected since etcd backend in v2.3 still implements pre-V1 behavior

**Comment by discsthnew** [comment]
Thanks for your answer @gyliu513 @gyliu513 ,  it seems to that i need wait for next release.

**Comment by gunjan5** [comment]
@discsthnew it should be out any day now.

**Comment by gyliu513** [comment]
@gunjan5 Thanks!

While, I was a bit confused by the CHANGELOG here https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#network , it was mentioning that the `net.beta.kubernetes.io/network-policy annotation on Namespaces (used to opt in to isolation) has been removed`, but it actually still works with Kubernetes 1.7, is it a bug for CHANGELOG?

-----------------------
NetworkPolicy has been promoted from extensions/v1beta1 to the new networking.k8s.io/v1 API group. The structure remains unchanged from the v1beta1 API. The net.beta.kubernetes.io/network-policy annotation on Namespaces (used to opt in to isolation) has been removed. 
-----------------------

**Comment by tmjd** [comment]
@gyliu513 I agree that can be a bit confusing but as gunjan5 pointed out it is a change to the API for NetworkPolicy, the change though is to not honor an annotation.  Annotations though are just key value pairs so 1.7 cannot reject the annotation since an annotation could have anything.

Part of the confusion here, I believe, is that K8s is just defining the API and what they are suppose to mean and it is up to the pieces implementing the policy to interpret the API appropriately.  So you could say that this is a bug that exists with Calico 2.3 when using etcd with k8s 1.7 and the work around is to just use the K8s 1.6 NetworkPolicy Spec.  The fix is coming with https://github.com/projectcalico/k8s-policy/pull/105 which has been merged to master and will be out with the Calico 2.4 release.

**Comment by caseydavenport** [comment]
I've just release v0.7.0 which should fix this issue - please give it a shot and let me know if you find any problems!

Thanks.

**Comment by gyliu513** [comment]
@caseydavenport , so 2.4 can work with etcd datastore, right? Can you please show more detail for how to get the latest binries for test? Such as calicoctl, calico node, cni plugin etc, just like http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/integration mentioned here, then I can do some test with v2.4 to see if it works.

**Comment by caseydavenport** [comment]
If you'd like to try it out, the 2.4 docs are available here: http://docs.projectcalico.org/v2.4/getting-started/kubernetes/installation/integration

Do note that it's still pre-release, so not production ready and there may still be bugs.  Please report them if you find them!

**Comment by gyliu513** [comment]
@caseydavenport one question want to get your help, after test with calico 2.4, the network policy works well, but I found that the `ingress` rules are different with `calicoctl get profile` and `kubectl get networkpolicies`. The `calicoctl get profile` does not list any ingress rules but the `kubectl get networkpolicies` can show all policies, can you please explain why? Thanks!

Profile for `default` namespace
```
root@k8s001:~/calico2.4# calicoctl get profile  k8s_ns.default  -o yaml
- apiVersion: v1
  kind: profile
  metadata:
    name: k8s_ns.default
    tags:
    - k8s_ns.default
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
```

Network Policy for `default` namespace
```
root@k8s001:~/calico2.4# kubectl get networkpolicies
NAME           POD-SELECTOR   AGE
access-nginx   run=nginx      3m
root@k8s001:~/calico2.4# kubectl get networkpolicies -oyaml
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: NetworkPolicy
  metadata:
    creationTimestamp: 2017-07-27T16:19:18Z
    generation: 1
    name: access-nginx
    namespace: default
    resourceVersion: "186862"
    selfLink: /apis/extensions/v1beta1/namespaces/default/networkpolicies/access-nginx
    uid: 577cb2f7-72e7-11e7-bd1e-08002759511a
  spec:
    ingress:
    - from:
      - podSelector:
          matchLabels:
            access: "true"
    podSelector:
      matchLabels:
        run: nginx
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by caseydavenport** [comment]
@gyliu513 try `calicoctl get policy` instead

**Comment by gyliu513** [comment]
@caseydavenport this works

```
root@k8s001:/opt/cni/bin# calicoctl get policy default.access-nginx -o yaml
- apiVersion: v1
  kind: policy
  metadata:
    name: default.access-nginx
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source:
        selector: access == 'true' && calico/k8s_ns == 'default'
    order: 1000
    selector: calico/k8s_ns == 'default' && run == 'nginx'
```

Just curiois why does the `calicoctl get profile` does not include the policy? I recalled that if we define `deny-all` policy, then the `ingress` rules will be reflected in `calicoctl get profile` as `deny`.
