### ISSUE TITLE
With Egress rule intercommunication POD not working

### ISSUE THREAD

**Issue by prasenforu** [projectcalico/k8s-policy#119]
## Environment
* Operating System and version: Ubuntu 16.4
* Kubernetes using kubeadm
* Version: 1.7.2
* Calicoctl version: 2.4
Deploy k8s policy:

Below egress policy only allow external db running on port 3306 & 3307

```
- apiVersion: v1
  kind: policy
  metadata:
    name: egress-allow-from-denyapp-to-external-db-3306
  spec:
    egress:
    - action: allow
      protocol: tcp
      destination:
        net: 172.31.18.58/32
        ports: 
        - 3306
    order: 501
    Selector: calico/k8s_ns == 'denyapp'
- apiVersion: v1
  kind: policy
  metadata:
    name: egress-allow-from-test-security-to-external-db-3307
  spec:
    egress:
    - action: allow
      protocol: tcp
      destination:
        net: 172.31.18.58/32
        ports: 
        - 3307
    order: 502
    Selector: calico/k8s_ns == 'test-security'
EOF
```
Its working as per expectation but I want intercommunication in kubernetes cluster.

So I deploy below policy as per documentation.

```
calicoctl apply -f - <<EOF
apiVersion: v1
kind: policy
metadata:
  name: policy-allow-dns
spec:
  selector: calico/k8s_ns == 'test-security' && calico/k8s_ns == 'denyapp'
  order: 400
  egress:
  - action: allow
    protocol: udp
    destination:
      selector: calico/k8s_ns == 'kube-system' && k8s-app == 'kube-dns'
      ports: [53]
EOF
```

But intercommunication inside kubernetes cluster not working not even same namespace

**Comment by tmjd** [comment]
I believe you need to specify some ingress policy to allow incoming traffic to your pods.  With any policy selecting a pod then it by default has ingress traffic denied.

**Comment by prasenforu** [comment]
Then not sure what ```policy-allow-dns``` with ```order 400``` doing.

It should for inter communication within same namespace.

**Comment by tmjd** [comment]
That allows egress (outbound) traffic from a pod, but has no allowances for ingress (inbound) traffic.  That specific rule applies to the pods matching `selector: calico/k8s_ns == 'test-security' && calico/k8s_ns == 'denyapp'` and says that if there is traffic leaving the pods destined for pods matching `selector: calico/k8s_ns == 'kube-system' && k8s-app == 'kube-dns'` on UDP port 53, then the traffic will be allowed, that is the only traffic `policy-allow-dns` allows.  There are no provisions to allow any inbound traffic.
If you want to allow all traffic between pods in the `test-security` namespace then I think you would need something like the following
```
calicoctl apply -f - <<EOF
apiVersion: v1
kind: policy
metadata:
  name: policy-allow-dns
spec:
  selector: calico/k8s_ns == 'test-security'
  order: 400
  ingress:
  - action: allow
    source:
      selector: calico/k8s_ns == 'test-security'
  egress:
  - action: allow
    destination:
      selector: calico/k8s_ns == 'test-security'
EOF
```
