### ISSUE TITLE
Calico policy for Openshift platform 

### ISSUE THREAD

**Issue by prasenforu** [projectcalico/k8s-policy#141]
Openshit Origin 3.6
CentOS 3.7
Ansible 2.3
docker 1.12.6
kubectl 1.6.1

Installation based on 4 node Cluster [1 Master, 1 Hub/Infra (Router running), 2 Node]

In Openshift ```router``` is a POD in ```default``` namespace which forward external call to Service then PoD. So  in openshift if ANY service expose then only outside openshift network can communicate particularly that service, as below.

Outside -> Router (default namespace) -> service -> POD

 #### What I am trying to do, 

Below egress policy only allow external db running on port 3306 & 3307.

```
calicoctl apply -f - <<EOF
- apiVersion: v1
  kind: policy
  metadata:
    name: allow-router
  spec:
    ingress:
    - action: allow
      source:
        selector: calico/k8s_ns == 'default' && calico/k8s_ns == 'kube-system'
    egress:
    - action: allow
      destination:
        selector: calico/k8s_ns == 'default' && calico/k8s_ns == 'kube-system'
    order: 400
    Selector: calico/k8s_ns == 'allow3306' && calico/k8s_ns == 'allow3307' 
- apiVersion: v1
  kind: policy
  metadata:
    name: allow3306-to-external-db-3306
  spec:
    egress:
    - action: allow
      protocol: tcp
      destination:
        selector: calico/k8s_ns == 'test-db'
        ports:
        - 3306
    - action: allow
      protocol: tcp
      destination:
        net: 10.90.1.222/32
        ports:
        - 3306
    order: 500
    Selector: calico/k8s_ns == 'allow3306'
- apiVersion: v1
  kind: policy
  metadata:
    name: allow3307-to-external-db-3307
  spec:
    egress:
    - action: allow
      protocol: tcp
      destination:
        selector: calico/k8s_ns == 'test-db'
        ports:
        - 3306
    - action: allow
      protocol: tcp
      destination:
        net: 10.90.1.222/32
        ports:
        - 3307
    order: 501
    Selector: calico/k8s_ns == 'allow3307'
EOF
```
###### Without these policy I am able to ping from router POD to all PODs but once I deploy this policy there are no communication from router POD to allow3307, allow3306 but rest other pod communications OK.

```
[root@ose-master ~]# oc get pod --all-namespaces -o wide
NAMESPACE     NAME                                        READY     STATUS    RESTARTS   AGE       IP             NODE
allow3306     app-b-allow3306-1-cx3z8                     1/1       Running   2          1d        10.5.135.31    ose-node1.cloud-cafe.in
allow3307     app-a-allow3307-1-n2t0r                     1/1       Running   2          1d        10.5.135.29    ose-node1.cloud-cafe.in
default       docker-registry-1-j3tq8                     1/1       Running   2          1d        10.5.157.202   ose-hub.cloud-cafe.in
default       mongo                                       1/1       Running   2          1d        10.5.157.203   ose-hub.cloud-cafe.in
default       myemp-1-4r016                               1/1       Running   2          1d        10.5.129.150   ose-node2.cloud-cafe.in
default       router-1-bqp9x                              2/2       Running   10         1d        10.90.1.209    ose-hub.cloud-cafe.in
denydball     web-server-1-5qckp                          1/1       Running   2          1d        10.5.135.30    ose-node1.cloud-cafe.in
kube-system   calico-policy-controller-4072784145-zd6jj   1/1       Running   10         2d        10.90.1.208    ose-master.cloud-cafe.in
test-db       demodb-1-m2z6m                              1/1       Running   1          18h       10.5.129.151   ose-node2.cloud-cafe.in
[root@ose-master ~]# oc rsh router-1-bqp9x sh
Defaulting container name to router.
sh-4.2$ ping 10.5.135.31
PING 10.5.135.31 (10.5.135.31) 56(84) bytes of data.
^C
--- 10.5.135.31 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 1999ms

sh-4.2$ ping 10.5.135.29
PING 10.5.135.29 (10.5.135.29) 56(84) bytes of data.
^C
--- 10.5.135.29 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 1999ms

sh-4.2$ ping 10.5.135.30
PING 10.5.135.30 (10.5.135.30) 56(84) bytes of data.
64 bytes from 10.5.135.30: icmp_seq=1 ttl=63 time=1.43 ms
64 bytes from 10.5.135.30: icmp_seq=2 ttl=63 time=1.45 ms
^C
--- 10.5.135.30 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 1.438/1.448/1.459/0.039 ms
```
##### What I noticed after implementing this policy it works as per rules ```allow3307-to-external-db-3307``` & ```allow3306-to-external-db-3306```
```
[root@ose-master ~]# oc rsh po/app-b-allow3306-1-cx3z8 sh
# curl -v telnet://10.90.1.222:3306
* Rebuilt URL to: telnet://10.90.1.222:3306/
* Hostname was NOT found in DNS cache
*   Trying 10.90.1.222...
* Connected to 10.90.1.222 (10.90.1.222) port 3306 (#0)
J
* RCVD IAC EC
* RCVD IAC 129
^C
# curl -v telnet://10.5.129.151:3306
* Rebuilt URL to: telnet://10.5.129.151:3306/
* Hostname was NOT found in DNS cache
*   Trying 10.5.129.151...
* Connected to 10.5.129.151 (10.5.129.151) port 3306 (#0)
[
* RCVD IAC EC
^C
# curl -v telnet://10.90.1.222:3307
* Rebuilt URL to: telnet://10.90.1.222:3307/
* Hostname was NOT found in DNS cache
*   Trying 10.90.1.222...
^C
```

#### What I am looking, pods from ```default``` namespace should allow ALL communication to ANY PODs

Same type of scenario I tested in kubernetes with calico and it woks but facing challenges in OpenShift.

In that case difference between kubernetes and openshift is,

In OpenShift use Router & in Kubernetes it uses Ingress controler.

**Comment by prasenforu** [comment]
Same type of scenario I tested in kubernetes with calico and it woks but facing challenges in OpenShift.

In that case difference between kubernetes and openshift is,

In OpenShift use Router & in Kubernetes it uses Ingress controler.

**Comment by prasenforu** [comment]
After little diagnosis I found if any service having multiple in a namespaces then traffic is not going through.

```
[root@ose-master ~]# oc get svc,pod --all-namespaces -o wide
NAMESPACE   NAME                  CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE       SELECTOR
allow3306   svc/app-b-allow3306   172.30.96.130    <none>        80/TCP                    4d        name=app-b-allow3306
allow3307   svc/app-a-allow3307   172.30.89.104    <none>        80/TCP                    4d        name=app-a-allow3307
default     svc/docker-registry   172.30.105.115   <none>        5000/TCP                  4d        docker-registry=default
default     svc/kubernetes        172.30.0.1       <none>        443/TCP,53/UDP,53/TCP     5d        <none>
default     svc/mongo             172.30.7.77      <none>        27017/TCP                 4d        context=docker-pkar,name=mongo
default     svc/myemp             172.30.200.91    <none>        80/TCP                    4d        context=docker-pkar,deploymentconfig=myemp,name=myemp
default     svc/router            172.30.184.118   <none>        80/TCP,443/TCP,1936/TCP   5d        router=router
denydball   svc/web-server        172.30.119.121   <none>        80/TCP                    4d        name=web-server
test-db     svc/demodb            172.30.200.203   <none>        3306/TCP                  3d        name=demodb
```

If you look above output ``svc/kubernetes`` & ```svc/router``` multiple port number involved.

```
default     svc/kubernetes        172.30.0.1           <none>        443/TCP,53/UDP,53/TCP
default     svc/router                172.30.184.118   <none>        80/TCP,443/TCP,1936/TCP
```

#### In that scenario calico policy NOT working.

I tried with define port and selector as follows but no luck.

```
calicoctl apply -f - <<EOF
apiVersion: v1
kind: policy
metadata:
  name: allow-dns1
spec:
  selector: calico/k8s_ns == 'allow3306'
  order: 400
  egress:
  - action: allow
    protocol: udp
    destination:
      selector: calico/k8s_ns == 'default' && router == 'router'
      ports: [80]
EOF
```

**Comment by ozdanborne** [comment]
@prasenforu Sorry for the delay, but I have time dedicated to get to the bottom of this this week.

For starters, it looks to me like the selector for `allow-router` is wrong. It's currently set to `calico/k8s_ns == 'allow3306' && calico/k8s_ns == 'allow3307'` which won't match anything. I think you want `||` instead of `&&`. Same for each of the rule selectors in that policy.

However, its not clear to me what the purpose of that policy is. Router is a host networked pod, so calico policy does not apply to it, and other policies will not be able to reference it using selectors.

**Comment by prasenforu** [comment]
I tried all combination but noticed if I apply these two policy ``` allow3306-to-external-db-3306``` & ``` allow3307-to-external-db-3307``` no traffic moving ```to & from ``` default namespace.

What I want whatever policy I put in this environment ```pods from default namespace should allow ALL communication to ANY PODs```

Can help me on that & what would be that poilicy?

**Comment by ozdanborne** [comment]
>In Openshift router is a POD in default namespace which forward external call to Service then PoD. So in openshift if ANY service expose then only outside openshift network can communicate particularly that service, as below.

That might be the default behavior of OVS, but it is not he default behavior of Calico. Calico won't block traffic unless networkpolicy specifies that it should be blocked.

Again, the router is a host networked pod. So WRT "All pods from default namespace should allow ANY communication to ANY PODs in the cluster", simply delete all policy in the default namespace, and you will have achieved your desired effect (at least from an outbound perspective).

**Comment by prasenforu** [comment]
After adding following part, now I am able to do what I am expecting.

```
ingress:
    - action: allow
      protocol: tcp
      destination:
        ports:
        - 80
```
Thanks Dan for your kind support.
