### ISSUE TITLE
Could not find etcd hosts

### ISSUE THREAD

**Issue by devent** [projectcalico/k8s-policy#87]
I followed the guide https://github.com/coreos/coreos-kubernetes/tree/master/multi-node/generic on how to install Kubernetes with Calico CNI. Everything works fine until the `quay.io/calico/kube-policy-controller:v0.5.4` pod. For some reason it can not find my etcd endpoint hosts.

It looks like issue #69, but I'm using the never version 0.5.4. And the error is not a certificate error but that the hosts can not be found.

```
                "ETCD_ENDPOINTS=https://etcd-0.robobee.test:2379,https://etcd-1.robobee.test:2379",
                "ETCD_CA_CERT_FILE=/calico-secrets/etcd-ca",
                "ETCD_KEY_FILE=/calico-secrets/etcd-key",
                "ETCD_CERT_FILE=/calico-secrets/etcd-cert",
```

```
root@andrea-node-0-local:~# etcdctl endpoint health
2017-03-28 16:31:46.022639 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
2017-03-28 16:31:46.026442 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
https://etcd-0.robobee.test:2379 is healthy: successfully committed proposal: took = 81.130864ms
https://etcd-1.robobee.test:2379 is healthy: successfully committed proposal: took = 72.112495ms
```

Error

```
root@andrea-node-0-local:~# docker logs 9d5155b370b5
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "handlers/network_policy.py", line 12, in <module>
  File "site-packages/pycalico/datastore.py", line 251, in __init__
  File "site-packages/etcd/client.py", line 202, in __init__
  File "site-packages/etcd/client.py", line 302, in machines
  File "site-packages/etcd/client.py", line 304, in machines
etcd.EtcdException: Could not get the list of servers, maybe you provided the wrong host(s) to connect to?
controller returned -1
```

What I don't understand, why is in the CNI calico configuration file the paths to the Etcd certificates are `/etc/cni/net.d/calico-tls/etcd-key` but the certificates are in `/etc/kubernetes/cni/net.d/calico-tls`. Is that a problem?

```
root@andrea-node-0-local:/etc/kubernetes/cni/net.d/calico-tls# pwd
/etc/kubernetes/cni/net.d/calico-tls
root@andrea-node-0-local:/etc/kubernetes/cni/net.d/calico-tls# ls -l
total 16
-rw-r--r-- 1 root root 6457 Mar 28 15:49 etcd-ca
-rw-r--r-- 1 root root 2260 Mar 28 15:49 etcd-cert
-rw-r--r-- 1 root root 3243 Mar 28 15:49 etcd-key
```

```
root@andrea-node-0-local:/etc/kubernetes/cni/net.d# cat 10-calico.conf
{
    "name": "calico",
    "type": "flannel",
    "delegate": {
      "type": "calico",
      "etcd_endpoints": "https://etcd-0.robobee.test:2379,https://etcd-1.robobee.test:2379",
      "etcd_key_file": "/etc/cni/net.d/calico-tls/etcd-key",
      "etcd_cert_file": "/etc/cni/net.d/calico-tls/etcd-cert",
      "etcd_ca_cert_file": "/etc/cni/net.d/calico-tls/etcd-ca",
      "log_level": "info",
      "policy": {
          "type": "k8s",
          "k8s_api_root": "https://10.3.0.1:443",
          "k8s_auth_token": "xxx"
      },
      "kubernetes": {
          "kubeconfig": "/etc/kubernetes/cni/net.d/calico-kubeconfig"
      }
    }
}
```

**Comment by devent** [comment]
Update.
If I specify IP addresses, the hosts are found and Calico runs now. Why can't it resolve the Etcd host names? Doesn't kube-policy-controller uses the DNS server listed in `/etc/resolve.conf` ?

But now I get the following errors from the quay.io/calico/kube-policy-controller:v0.5.4 pod. Is that Etcd certificate errors or Kubernetes certificate errors?

```
2017-03-28 15:34:56,879 7 INFO Syncing 'Namespace' objects
2017-03-28 15:34:56,975 7 INFO Syncing 'Pod' objects
2017-03-28 15:34:56,995 7 INFO Syncing 'NetworkPolicy' objects
2017-03-28 15:34:57,091 7 WARNING Connection error: Namespace ...("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
2017-03-28 15:34:57,095 7 INFO Restarting watch on resource: Namespace
2017-03-28 15:34:57,173 7 WARNING Connection error: Pod ...("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
2017-03-28 15:34:57,211 7 INFO Restarting watch on resource: Pod
2017-03-28 15:34:57,212 7 WARNING Connection error: NetworkPolicy ...("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
2017-03-28 15:34:57,212 7 INFO Restarting watch on resource: NetworkPolicy
2017-03-28 15:34:58,099 7 INFO Syncing 'Namespace' objects
2017-03-28 15:34:58,189 7 WARNING Connection error: Namespace ...("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
2017-03-28 15:34:58,190 7 INFO Restarting watch on resource: Namespace
2017-03-28 15:34:58,212 7 INFO Syncing 'Pod' objects
2017-03-28 15:34:58,216 7 INFO Syncing 'NetworkPolicy' objects
2017-03-28 15:34:58,272 7 WARNING Connection error: Pod ...("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
2017-03-28 15:34:58,273 7 INFO Restarting watch on resource: Pod
2017-03-28 15:34:58,284 7 WARNING Connection error: NetworkPolicy ...("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
2017-03-28 15:34:58,284 7 INFO Restarting watch on resource: NetworkPolicy
```

Furthermore, I get the following errors from Kubernetes Pods.

```
  15m   2s      273     {kubelet andrea-node-0-local.robobee.test}              Warning FailedSync      Error syncing pod, skipping: failed to "SetupNetwork" for "kubernetes-dashboard-3543765157-lp51g_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kubernetes-dashboard-3543765157-lp51g_kube-system(b70d783a-13c6-11e7-80c0-08002726fb41)\" using network plugins \"cni\": open /etc/cni/net.d/calico-tls/etcd-cert: no such file or directory; Skipping pod"
```

I think the `10-calico.conf` is pointing to the wrong directory?

**Comment by tmjd** [comment]
Just to make sure we're on the same page, did you start from https://github.com/coreos/coreos-kubernetes/tree/master/multi-node/generic and then modified it to use the newer calico/kube-policy-controller and added certificates into the configuration also?

> What I don't understand, why is in the CNI calico configuration file the paths to the Etcd certificates are /etc/cni/net.d/calico-tls/etcd-key but the certificates are in /etc/kubernetes/cni/net.d/calico-tls. Is that a problem?

Those fields in `10-calico.conf` starting with `etcd_` are paths to the certificates for calico to use for connecting to etcd, not for connecting to the kubernetes API.  I would not expect the etcd certificates to be located under `/etc/kubernetes` but I could certainly be wrong.  If that is the location of the etcd certificates then yes that would be a problem.

> Is that Etcd certificate errors or Kubernetes certificate errors?

I wasn't familiar with the code but I believe, after looking, that the `bad handshake` errors are from the connection attempt to kubernetes.

I haven't set up etcd or kubernetes access with SSL so I can't help much more than what I've done.  @caseydavenport or @gunjan5 could one of you help with this?
@devent Since I am assuming you have modified what you linked in your OP could you share what you have created?  It might help make the process go much quicker.

**Comment by devent** [comment]
Yes, I started with https://github.com/coreos/coreos-kubernetes/tree/master/multi-node/generic and then added the Etcd certificates. I also fixed now `10-calico.conf` to change the paths of the Etcd certificates to `/etc/kubernetes/cni/net.d/calico-tls`. Now I'm at this point.

```
root@andrea-master-local:~# kubectl get pods --all-namespaces
NAMESPACE     NAME                                          READY     STATUS             RESTARTS   AGE
kube-system   calico-node-9kx7q                             2/2       Running            0          2h
kube-system   calico-policy-controller-279105993-6qcjf      1/1       Running            0          3h
kube-system   heapster-v1.2.0-216693398-vh308               2/2       Running            0          3h
kube-system   kube-apiserver-192.168.56.200                 1/1       Running            0          7s
kube-system   kube-controller-manager-192.168.56.200        1/1       Running            2          7s
kube-system   kube-dns-782804071-9dv22                      3/4       CrashLoopBackOff   71         3h
kube-system   kube-dns-autoscaler-2715466192-g0g99          1/1       Running            0          3h
kube-system   kube-proxy-192.168.56.200                     1/1       Running            0          7s
kube-system   kube-proxy-andrea-node-0-local.robobee.test   1/1       Running            0          2h
kube-system   kube-scheduler-192.168.56.200                 1/1       Running            2          6s
kube-system   kubernetes-dashboard-3543765157-lpr9h         0/1       CrashLoopBackOff   34         3h
```

But I still get the same errors from calico-controller.

```
2017-03-29 11:13:08,029 7 WARNING Connection error: NetworkPolicy ...("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
2017-03-29 11:13:08,029 7 INFO Restarting watch on resource: NetworkPolicy
2017-03-29 11:13:08,488 7 INFO Syncing 'Namespace' objects
2017-03-29 11:13:08,530 7 WARNING Connection error: Namespace ...("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
2017-03-29 11:13:08,531 7 INFO Restarting watch on resource: Namespace
2017-03-29 11:13:08,639 7 INFO Syncing 'Pod' objects
2017-03-29 11:13:08,680 7 WARNING Connection error: Pod ...("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
2017-03-29 11:13:08,680 7 INFO Restarting watch on resource: Pod
````

Here is the calico manifest.
```
# This ConfigMap is used to configure a self-hosted Calico installation.
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  # Configure this with the location of your etcd cluster.
  etcd_endpoints: "https://etcd:2379"

  # Configure the Calico backend to use.
  calico_backend: "none"

  # Path of the CNI net directory.
  cni_net_dir: "/etc/kubernetes/cni/net.d"

  # The CNI network configuration to install on each node.  The special
  # values in this config will be automatically populated.
  cni_network_config: |-
    {
        "name": "calico",
        "type": "flannel",
        "delegate": {
          "type": "calico",
          "etcd_endpoints": "__ETCD_ENDPOINTS__",
          "etcd_key_file": "__ETCD_KEY_FILE__",
          "etcd_cert_file": "__ETCD_CERT_FILE__",
          "etcd_ca_cert_file": "__ETCD_CA_CERT_FILE__",
          "log_level": "info",
          "policy": {
              "type": "k8s",
              "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
              "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
          },
          "kubernetes": {
              "kubeconfig": "/etc/kubernetes/cni/net.d/__KUBECONFIG_FILENAME__"
          }
        }
    }
  # If you're using TLS enabled etcd uncomment the following.
  # You must also populate the Secret below with these files.
  etcd_ca: "/calico-secrets/etcd-ca"   # "/calico-secrets/etcd-ca"
  etcd_cert: "/calico-secrets/etcd-cert" # "/calico-secrets/etcd-cert"
  etcd_key: "/calico-secrets/etcd-key"  # "/calico-secrets/etcd-key"

---

# The following contains k8s Secrets for use with a TLS enabled etcd cluster.
# For information on populating Secrets, see http://kubernetes.io/docs/user-guide/secrets/
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: calico-etcd-secrets
  namespace: kube-system
data:
  # Populate the following files with etcd TLS configuration if desired, but leave blank if
  # not using TLS for etcd.
  # This self-hosted install expects three files with the following names.  The values
  # should be base64 encoded strings of the entire contents of each file.
  etcd-key: LS0tLS1CRUdJTiBSU0Eg...QVRFIEtFWS0tLS0tCg==
  etcd-cert: LS0tLS1CRUdJTiBDRVJ...tLS0tCg==
  etcd-ca: LS0tLS1CRUdJTiBDRVJUS...RFLS0tLS0K

---

# This manifest installs the calico/node container, as well
# as the Calico CNI plugins and network config on
# each master and worker node in a Kubernetes cluster.
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    k8s-app: calico-node
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
  template:
    metadata:
      labels:
        k8s-app: calico-node
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: |
          [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
           {"key":"CriticalAddonsOnly", "operator":"Exists"}]
    spec:
      hostNetwork: true
      containers:
        # Runs calico/node container on each Kubernetes node.  This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: quay.io/calico/node:v1.1.0
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Choose the backend to use.
            - name: CALICO_NETWORKING_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: calico_backend
            # Disable file logging so `kubectl logs` works.
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            - name: NO_DEFAULT_POOLS
              value: "true"
            # Location of the CA certificate for etcd.
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
            # Location of the client key for etcd.
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            # Location of the client certificate for etcd.
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /var/run/calico
              name: var-run-calico
              readOnly: false
            - mountPath: /calico-secrets
              name: etcd-certs
            - mountPath: /etc/resolv.conf
              name: dns
              readOnly: true
        # This container installs the Calico CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: quay.io/calico/cni:v1.6.2
          imagePullPolicy: Always
          command: ["/install-cni.sh"]
          env:
            # CNI configuration filename
            - name: CNI_CONF_NAME
              value: "10-calico.conf"
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # The CNI net dir.
            - name: CNI_NET_DIR
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: cni_net_dir
            # The CNI network config to install on each node.
            - name: CNI_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: cni_network_config
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
            - mountPath: /calico-secrets
              name: etcd-certs
      volumes:
        # Used by calico/node.
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: var-run-calico
          hostPath:
            path: /var/run/calico
        # Used to install CNI.
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/kubernetes/cni/net.d
        - name: dns
          hostPath:
            path: /etc/resolv.conf
        # Mount in the etcd TLS secrets.
        - name: etcd-certs
          secret:
            secretName: calico-etcd-secrets

---

# This manifest deploys the Calico policy controller on Kubernetes.
# See https://github.com/projectcalico/k8s-policy
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calico-policy-controller
  namespace: kube-system
  labels:
    k8s-app: calico-policy
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
    scheduler.alpha.kubernetes.io/tolerations: |
      [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
       {"key":"CriticalAddonsOnly", "operator":"Exists"}]
spec:
  # The policy controller can only have a single active instance.
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: calico-policy-controller
      namespace: kube-system
      labels:
        k8s-app: calico-policy
    spec:
      # The policy controller must run in the host network namespace so that
      # it isn't governed by policy that would prevent it from working.
      hostNetwork: true
      containers:
        - name: calico-policy-controller
          image: quay.io/calico/kube-policy-controller:v0.5.4
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Location of the CA certificate for etcd.
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
            # Location of the client key for etcd.
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            # Location of the client certificate for etcd.
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
            # The location of the Kubernetes API.  Use the default Kubernetes
            # service for API access.
            - name: K8S_API
              value: "https://kubernetes.default:443"
            # Since we're running in the host namespace and might not have KubeDNS
            # access, configure the container's /etc/hosts to resolve
            # kubernetes.default to the correct service clusterIP.
            - name: CONFIGURE_ETC_HOSTS
              value: "true"
          volumeMounts:
            # Mount in the etcd TLS secrets.
            - mountPath: /calico-secrets
              name: etcd-certs
      volumes:
        # Mount in the etcd TLS secrets.
        - name: etcd-certs
          secret:
            secretName: calico-etcd-secrets
```

Generated files.

```
root@andrea-node-0-local:/etc/kubernetes/cni/net.d# ls
10-calico.conf  10-flannel.conf  calico-kubeconfig  calico-tls
root@andrea-node-0-local:/etc/kubernetes/cni/net.d# cat calico-kubeconfig 
# Kubeconfig file for Calico CNI plugin.
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    insecure-skip-tls-verify: true
users:
- name: calico 
contexts:
- name: calico-context
  context:
    cluster: local
    user: calico 
current-context: calico-context
```

Don't I need in the `calico-kubeconfig` my client certificate? My apiserver is only reachable via 443.
